### ISSUE TITLE
how to merge different .ckpt files into a .pb file

### ISSUE THREAD

**Issue by Michael3444** [blaueck/tf-mtcnn#1]
I had trained PNet, RNet, ONet separately and saved them into .ckpt files, I want to merge these three .ckpt files into a .pb file . can you tell me how to finish that?

**Comment by blaueck** [comment]
If you just want to merge three network into one .pb file and do pre/post-processing (like nms, resizing images, etc.) outside tensorflow graph (like in [this link](https://github.com/davidsandberg/facenet/blob/master/src/align/detect_face.py)):
```python
'''
Basic idea:
1. Define three network in one tensorflow graph
2. Restore weights stored in the .ckpt files
3. Save the graph to a .pb file
''' 
# define PNet, RNet, ONet
pnet_outputs = PNet(...)
rnet_outputs = RNet(...)
onet_outputs = ONet(...)

# restore weights
pnet_saver = tf.train.Saver(var_list=tf.global_variables("<variable name scope of pnet>"))
pnet_saver.restore("<path to .ckpt file without suffix>")
# do the same for rnet and onet.....

sess = tf.Session()
sess.run(tf.global_variables_initializer())

# save graph to pb file
src_graph = tf.get_default_graph()
src_graph_def = src_graph.as_graph_def()
# assume all the output of three networks is a list of tensors
output_tensors = pnet_outputs + rnet_outputs + onet_outputs

dst_graph_def = tf.graph_util.convert_variables_to_constants(
        sess, src_graph_def, [t.op.name for t in output_tensors])
with open("<the file name you what to save", "wb") as f:
        f.write(dst_graph_def.SerializeToString())
```
If you what to do pre/post-processing inside tensorflow graph, you can add corresponding
operations when define the networks. For detail about the operations (like nms, images resizing, etc.), see [this link](https://github.com/blaueck/tf-mtcnn/blob/master/caffe2tf.py).

**Comment by Michael3444** [comment]
@blaueck thx bro, that's very kind of you ,you helped me a lot

**Comment by blaueck** [comment]
@Michael3444 , you are welcome.
