### ISSUE TITLE
AttributeError: 'Net' object has no attribute 'layer_dict'

### ISSUE THREAD

**Issue by f2fish** [blaueck/tf-mtcnn#2]
Hello 

I try to run the caffe2tf.py and download the caffe model from: https://github.com/kpzhang93/MTCNN_face_detection_alignment/tree/master/code/codes/MTCNNv1/model

>>>python3 caffe2tf.py ./caffemodel/ ./caffemodel/
and I got the error:
AttributeError: 'Net' object has no attribute 'layer_dict'

then I search for the function layer_dirct in the Caffe::Net, but I can't find it.
Did I miss something or how can I fix this ?

**Comment by blaueck** [comment]
Which version are you using? "layer_dict" is not defined in c++ source code, but in python. See the link: https://github.com/BVLC/caffe/blob/16467ff149c880f752414ee2c241c01040d1a05f/python/caffe/pycaffe.py#L334

**Comment by f2fish** [comment]
You remind me to check where is my caffe from ?
there is no error when I import caffe in python.
I check the caffe source, it is from the intel movidius.
I am replacing it .

thank you, you really did a great job for this project.

**Comment by blaueck** [comment]
I'm glad this project is helpful.

**Comment by f2fish** [comment]
I reinstall caffe, and it work well.
thank you.

**Comment by blaueck** [comment]
Glad to hear that it work.
