### ISSUE TITLE
What are the names of the input and output nodes?

### ISSUE THREAD

**Issue by JeromeWYCB** [blaueck/tf-mtcnn#4]
Are these the names of the input and output nodes?

Model filename: mtcnn_1.12.pb
inputs:  4 [<tf.Operation 'import/input' type=Placeholder>, <tf.Operation 'import/min_size' type=Placeholder>, <tf.Operation 'import/thresholds' type=Placeholder>, <tf.Operation 'import/factor' type=Placeholder>]

outputs:  7 [<tf.Operation 'import/onet/cond/switch_t' type=Identity>, <tf.Operation 'import/onet/cond/switch_f' type=Identity>, <tf.Operation 'import/rnet/cond/switch_t' type=Identity>, <tf.Operation 'import/rnet/cond/switch_f' type=Identity>, <tf.Operation 'import/prob' type=Identity>, <tf.Operation 'import/landmarks' type=Identity>, <tf.Operation 'import/box' type=Identity>]

**Comment by blaueck** [comment]
[Here](https://github.com/blaueck/tf-mtcnn/blob/b7ffa195d1cbc873e271a996cf929a032ef29610/mtcnn.py#L36) have the names of input and output. There are 4 inputs and 3 outputs that is needed. The specific name is depending on how you import the model. 
```python
# Will not have prefix name,
tf.import_graph_def(graph_def, name='')

# Names are prefixed with "import" (default behavior)
# The same as : tf.import_graph_def(graph_def, name='import')
tf.import_graph_def(graph_def)
```
