### ISSUE TITLE
Detection differences to facenet-mtcnn

### ISSUE THREAD

**Issue by lodemo** [blaueck/tf-mtcnn#5]
I want to migrate from the facenet-mtcnn version to tf-mtcnn so that i can deploy the model through tf-serving. Tf-serving works well with the provided .pb model, however, i noticed that there are minor differences in the output of the models. 

Slightly different bounding boxes are less of a problem, but i observed that for some images the facenet-mtcnn version correctly detects a face while tf-mtcnn fails to do so (same parameters).

I imagine its because of the different computation implementations? Facenet-mtcnn uses Python while tf-mtcnn only uses tensorflow methods. I tried to review the implementations for any major differences but only noticed the scale pyramid construction to be slightly different. However, even when changing this to the facenet construction, the results still failed for some images.

Do you have any idea why that might be and how could i potentially achieve more similar results to facenet-mtcnn?

Here are some example images from the LFW dataset that failed with tf-mtcnn but succeeded with facenet-mtcnn: 

![Abdoulaye_Wade_0002](https://user-images.githubusercontent.com/2711650/137210444-4f1bf8a8-4528-4c96-b640-4d1ce970d909.jpg)
![Abdul_Majeed_Shobokshi_0001](https://user-images.githubusercontent.com/2711650/137210494-a7034559-ad28-4e71-b575-84b1a6111edf.jpg)
![Abdullah_al-Attiyah_0001](https://user-images.githubusercontent.com/2711650/137210834-cbcf3e5f-2ff6-421c-adce-284e7b41071c.jpg)
![Adriana_Lima_0001](https://user-images.githubusercontent.com/2711650/137211352-8448f914-fc11-4463-aed7-c2119d8c94de.jpg)

All detected from the same image array representation in RGB using the same default parameters (20, 0.709, [ 0.6, 0.7, 0.7 ]).

**Comment by blaueck** [comment]
I think the problem is that you are using RGB image array as input, not BGR as in the demo code.  The .pb model uses the BGR format as default. To make .pb file use RGB as input, you can try this code:

```python
# This is tf v2 code
import tensorflow as tf

tf.compat.v1.disable_v2_behavior()

with open('./mtcnn.pb', 'rb') as f:
    graph_def = tf.compat.v1.GraphDef.FromString(f.read())

with tf.device('/cpu:0'):
    img_input = tf.compat.v1.placeholder(shape=[None, None, 3], dtype=tf.float32, name='input')
    img = img_input[:, :, ::-1]
    prob, landmarks, box = tf.compat.v1.import_graph_def(
        graph_def,
        input_map={
            'input:0': img
        },
        return_elements=[
            'prob:0',
            'landmarks:0',
            'box:0']
        , name='')
    print(box, prob, landmarks)

graph = tf.compat.v1.get_default_graph()
graph_def = graph.as_graph_def()
with open('mtcnn_rgb.pb', 'wb') as f:
    f.write(graph_def.SerializeToString())
```

**Comment by lodemo** [comment]
Of course.. what a stupid mistake. I blindly assumed tf-mtcnn must also take RGB that i didnt even check.
Using BGR, the detection rates are now the same, results are still slightly different but thats manageable.

Thank you!
